name: Build & Test
on:
  pull_request:
    types: [opened, ready_for_review, reopened, closed]
  schedule:
    - cron: "0 0 * * 5"
  push:
    paths:
      - ".github/workflows/bench.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      max-parallel: 2
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Fetch Dependencies
        run: cargo fetch
      - name: Benchmark
        run: cargo test --release -- --ignored --show-output
