name: Benchmark
on:
  pull_request:
    types: [opened, ready_for_review, reopened, closed]
  schedule:
    - cron: "0 0 * * 5"
  push:
    paths:
      - ".github/workflows/bench.yml"

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch Dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --release
      - name: Benchmark
        run: cargo test --release -- --ignored --show-output
